package my.com.mandrill.utilities.general.constant;

public enum RunningNumberModule {

	USER_REFERENCE, DEALER_APPLICATION, INSTITUTION_REF_NO, INSTITUTION_INCIDENT_REPORT_RUNNING_NUMBER,
	INSTITUTION_COMMUNITY_INVESTMENT_RUNNING_NUMBER

}