package my.com.mandrill.utilities.general.constant;

import lombok.Getter;

@Getter
public enum TemplateNameEnum {

	SMS_OTP("OTP"), SMS_ENQUIRY_SUBMISSION("ENQUIRY_SUBMISSION"), EMAIL_EMAIL_VERIFICATION("EMAIL_VERIFICATION"),
	EMAIL_EMAIL_UPDATED("EMAIL_UPDATED"), EMAIL_PASSWORD_UPDATED("PASSWORD_UPDATED"),
	EMAIL_RESET_PASSWORD("RESET_PASSWORD"), EMAIL_DEALER_POSTING_INTEREST("DEALER_POSTING_INTEREST"),
	EMAIL_DEALER_POSTING_OFFER("DEALER_POSTING_OFFER"), EMAIL_ENQUIRY_APPOINTMENT("ENQUIRY_APPOINTMENT"),
	EMAIL_OTP_VERIFICATION("OTP_VERIFICATION"), EMAIL_CONTACT_US("CONTACT_US"), EMAIL_SUPPORT("SUPPORT"),
	INSTITUTION_REGISTRATION("INSTITUTION_REGISTRATION"), SITE_ENTITY_REGISTRATION("SITE_ENTITY_REGISTRATION"),
	EMPLOYEE_INVITATION("EMPLOYEE_INVITATION"), VIEWER_INVITATION("VIEWER_INVITATION"),
	ADMIN_INVITATION("ADMIN_INVITATION"), NEW_SITE_ENTITY_REGISTRATION("NEW_SITE_ENTITY_REGISTRATION"),
	GRANT_SUPPORT_ADMIN("GRANT_SUPPORT_ADMIN"), UPDATE_ROLE("UPDATE_ROLE"),
	PCM_ADMIN_INVITATION("PCM_ADMIN_INVITATION"), COORDINATOR_INVITATION("COORDINATOR_INVITATION"),
	CLASSIFIER_INVITATION("CLASSIFIER_INVITATION"), EXISTING_USER_INVITATION("EXISTING_USER_INVITATION"),
	INSTITUTION_ACTIVATION("INSTITUTION_ACTIVATION"), SUPER_USER_INVITATION("SUPER_USER_INVITATION"),
	USER_INVITATION("USER_INVITATION");

	private final String value;

	TemplateNameEnum(String value) {
		this.value = value;
	}

}
