version: '3.8'
name: web-app-services
services:
  mta-db:
    image: postgres
    container_name: mta-db
    environment:
      POSTGRES_DB: darfatapp1
      POSTGRES_USER: darfatapp1
      POSTGRES_PASSWORD: darfatapp1
    ports:
      - "5432:5432"
    volumes:
      - mta-db:/var/lib/postgresql/data

  mta-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: mta-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - mta-zookeeper:/var/lib/zookeeper

  mta-broker:
    image: confluentinc/cp-kafka:latest
    container_name: mta-broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - mta-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'mta-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://mta-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "mta-broker:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - mta-broker:/var/lib/kafka

  mta-elasticsearch:
    container_name: mta-elasticsearch
    image: elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - mta-elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://mta-elasticsearch:9200/" ]
      interval: 30s
      timeout: 5s
      retries: 120

volumes:
  mta-db:
  mongo-db:
  mta-zookeeper:
  mta-broker:
  mta-elasticsearch:
